[package]
name = "swerve"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true
strip = "debuginfo"

[dependencies]
chrono = "0.4.38"
colored = "2.1.0"
gumdrop = "0.8.1"
mime_guess = "2.0.4"
tiny_http = "0.12.0"
