name: Build

on:
  push:
    paths:
      - '.github/workflows/build.yml'
      - 'Cargo.toml'
      - 'src/**/*'
      - 'web/**/*'
  pull_request:
    paths:
      - '.github/workflows/build.yml'
      - 'Cargo.toml'
      - 'src/**/*'
      - 'web/**/*'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.config.platform }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - platform: ubuntu-latest
            target: 'x86_64-unknown-linux-gnu'
          - platform: ubuntu-latest
            target: 'aarch64-unknown-linux-gnu'
          - platform: ubuntu-latest
            target: 'armv7-unknown-linux-gnueabihf'

          - platform: macos-latest
            target: 'x86_64-apple-darwin'
          - platform: macos-latest
            target: 'aarch64-apple-darwin'

          - platform: windows-latest
            target: 'x86_64-pc-windows-msvc'
          - platform: windows-latest
            target: 'aarch64-pc-windows-msvc'
    steps:
      - uses: actions-rust-lang/setup-rust-toolchain@v1.8
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ matrix.config.target }}-cargo-${{ hashFiles('Cargo.lock') }}

      - uses: actions/checkout@v4

      - name: Add targets
        run: rustup target add ${{ matrix.config.target }}
      
      - name: Build
        run: -|
          cargo build
            --release 
            --target ${{ matrix.config.target }}
            ${{ matrix.config.target != 'x86_64-unknown-linux-gnu' && '-C --linker=arm-linux-gnueabihf-gcc' || '' }}

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: swerve-${{ runner.os }}-${{ matrix.config.target }}
          path: target/${{ matrix.config.target }}/release/swerve

      - name: Upload (Windows)
        if: matrix.config.platform == 'windows-latest'
        uses: actions/upload-artifact@v2
        with:
          name: swerve-${{ runner.os }}-${{ matrix.config.target }}
          path: target/${{ matrix.config.target }}/release/swerve.exe