name: Release

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
    # tags:
    #   - 'v*.*.*'
    # TODO remove
    branches:
      - main
      
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Download all artifacts from the build job
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: Build
          path: artifacts

      - name: DEBUG list artifacts
        run: ls -la artifacts