name: Release

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
    # tags:
    #   - 'v*.*.*'
    # TODO remove
    branches:
      - main
      
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Download all artifacts from the build job
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: build.yml
          path: artifacts
          allow_forks: false
          branch: main

      - name: Rename executables to their folder names
        run: |
          # get the folder name
          folder_name=artifacts

          # get the list of inner folders
          folders=$(ls $folder_name)

          # loop through the files in each folder
          for folder in $folders
          do
              # get the list of files in the folder
              files=$(ls $folder_name/$folder)
              for file in $files
              do
                if [ $file == "*.exe"]
                then
                  mv $folder_name/$folder/$file $folder_name/$folder/$folder.exe
                else
                  mv $folder_name/$folder/$file $folder_name/$folder/$folder
                fi
              done
          done

      - name: Create release using all artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**
          token: ${{ secrets.GITHUB_TOKEN }}
          # Release name is the tag name
          name: ${{ github.ref_name }}
          body: |
            This is an automated release.
          draft: true
          prerelease: false
        